config/routes.rb
Rails.application.routes.draw do

  root 'access#menu'
  get 'fee/index'
  get 'sessions/new'
  get 'appointments/index'
  get 'payments/index'
  get 'access/menu'
  get 'candidates/index'
  get 'fees/new'
  post 'candidates/build'
  get 'candidates/select'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :eligibilities, except: [:show]
  resources :notices
  resources :users
  resources :fees
  resources :sections do

    resources :candidates do
      get 'manage', on: :member
      resources :appointments
      resources :payments
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :candidates, dependent: :destroy

  has_secure_password

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:index, :show, :edit, :update]
  before_action :correct_user_or_admin, only:[:edit, :update, :show]
  before_action :already_logged_in, only:[:new, :create]

  def index
    if current_user.admin?
      @users = User.paginate(page: params[:page], :per_page => 5)
    else
      flash[:notice] = "You are not authorized"
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:notice] = "Welcome"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.admin
      flash[:danger] = "Sorry, Admin can't be deleted."
      redirect_to users_path
    else
      @user.destroy
      flash[:notice] = "User deleted"
      redirect_to users_path
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user_or_admin
      @user = User.find(params[:id])
      unless current_user?(@user) || current_user.admin?
        redirect_to(root_url)
        flash[:danger]="You are not authorized to perform this action"
      end
    end

    def already_logged_in
      if current_user.present?
        flash[:notice] = "You are already logged in"
        redirect_to root_path
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>
<table class="table text-center">
  <tr>
    <td><%= f.label :name %></td>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td><%= f.label :email %></td>
    <td><%= f.email_field :email %></td>
  </tr>
  <tr>
    <td><%= f.label :password %></td>
    <td><%= f.password_field :password %></td>
  </tr>
  <tr>
    <td><%= f.label :password_confirmation, "Password Confirmation" %></td>
    <td><%= f.password_field :password_confirmation %></td>
  </tr>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2 class="text-center bg-info">Update Your account</h2>
      <%= form_for(@user) do |f| %>
        <%= render partial: 'form', locals: { f:f } %>
        <div class="text-center">
          <%= f.submit "Save changes", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container  text-center">
  <h2 class="text-center text-primary bg-info">Users</h2>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4 gray-border">
      <%= will_paginate %>
      <table class="table">
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, user %></td>
            <td class="text-left"><%= link_to "delete user", user, method: :delete, data: { confirm: "You sure?" },class:"btn btn-info btn-xs" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2 class="text-center bg-info">Sign up</h2>
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render partial: 'form', locals: { f:f } %>
        <div class="text-center">
          <%= f.submit "Create my account", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class ="container">
  <table class="table">
    <tr><h3 class="text-primary bg-gray">Candidates</h3></tr>
    <% if @user.candidates.size > 0 %>
      <% @user.candidates.each do |candidate| %>
        <tr>
          <td><%=link_to candidate.name, [candidate.section, candidate] %></td>
          <td><%= candidate.section.section_name %></td>
          <td><%= link_to "View appointment", section_candidate_appointment_path(candidate.section,candidate), class:"btn btn-sm btn-info"%></td>
          <% unless current_user.admin? %>
            <td><%= link_to "View payments", section_candidate_payments_path(candidate.section,candidate), class:"btn btn-sm btn-info" %></td>
          <% end %>
          <td><%= link_to "Edit candidate", edit_section_candidate_path(candidate.section, candidate), class:"btn btn-sm btn-info"%></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Destroy candidate', [candidate.section, candidate], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-info btn-sm text-danger' %></td>
          <% end %>
        </tr>
        </tr>
      <% end %>
    <% else %>
      <h4>You have not added any candidates</h4>
    <% end %>
  </table>
  <%= link_to "Add new candidate", candidates_select_path, class:"btn btn-primary" %>
  <%= link_to "View Admission status", candidates_index_path, class:"btn btn-primary" %>
</div>