config/routes.rb
Rails.application.routes.draw do

  root 'access#menu'
  get 'fee/index'
  get 'sessions/new'
  get 'appointments/index'
  get 'payments/index'
  get 'access/menu'
  get 'candidates/index'
  get 'fees/new'
  post 'candidates/build'
  get 'candidates/select'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :eligibilities, except: [:show]
  resources :notices
  resources :users
  resources :fees
  resources :sections do

    resources :candidates do
      get 'manage', on: :member
      resources :appointments
      resources :payments
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def menu
    @notices = Notice.all
    @eligibilities = Eligibility.all
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/menu.html.erb
<div class="banner hidden-xs">
  <%= image_tag 'slider.jpg' %>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-5 col-sm-offset-1 notice-eligibility">
      <div class="bg-light-blue gray-border notice">
        <h2 class="text-center heading bg-primary">NOTICE BOARD</h2>
        <ul>
          <% @notices.each do |notice| %>
            <li><%= link_to notice.notice_title, notice_path(notice), class:"text-big" %></li>
          <% end %>
        </ul>
        <br>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <p class="text-center"><%= link_to "Manage notices", notices_path, class:"btn btn-sm btn-info" %></p>
          <% end %>
        <% end %>
      </div>
      <div class="bg-light-blue gray-border eligibility">
        <h2 class="text-center heading bg-primary">ELIGIBILITY CRITERIA</h2>
        <ul>
          <% @eligibilities.each do |eligibility| %>
            <div class = "title-criteria">
              <li class="eligibility-title text-big"><%= eligibility.title %></li>
              <ul class="list-unstyled">
                <li class="criteria"><%= eligibility.criteria %></li>
              </ul>
            </div>
          <% end %>
        </ul>
        <br>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <p class="text-center"><%= link_to "Manage eligibility criteria", eligibilities_path, class:"btn btn-sm btn-info" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-3 col-sm-offset-3 nav-links">
      <h3 class="bg-info link shadow"><a href="<%= candidates_select_path %>">Apply for admission &raquo;</a></h3>
      <h3 class="bg-info link shadow"><a href="<%= sections_path %>">Sections &raquo;</a></h3>
      <h3 class="bg-info link shadow"><a href="<%= fees_path %>">Fee structure &raquo;</a></h3>
      <h3 class="bg-info link shadow"><a href="<%= candidates_index_path %>">Admission status &raquo;</a></h3>
    </div>
  </div>
</div>