config/routes.rb
Rails.application.routes.draw do

  root 'access#menu'
  get 'fee/index'
  get 'sessions/new'
  get 'appointments/index'
  get 'payments/index'
  get 'access/menu'
  get 'candidates/index'
  get 'fees/new'
  post 'candidates/build'
  get 'candidates/select'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :eligibilities, except: [:show]
  resources :notices
  resources :users
  resources :fees
  resources :sections do

    resources :candidates do
      get 'manage', on: :member
      resources :appointments
      resources :payments
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate.rb
class Candidate < ApplicationRecord

  has_one :appointment, dependent: :destroy
  has_many :payments, dependent: :destroy
  belongs_to :section
  belongs_to :user

  has_attached_file :image, styles: { thumb: "100x100#" }
  has_attached_file :marksheet, styles: { ex_large: "1000x1000>", medium: "300x300>" }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :marksheet, content_type: /\Aimage\/.*\z/
  validates :name, :father_name, :mother_name , presence: true, length: { maximum: 50 }
  validates :education, :contact_address, :parent_contact_number,:image, presence: true
  validates :parent_contact_number,:alternate_parent_contact_number, numericality: true, format: { with: /\A[789]\d{9}\z/ }
  validates_size_of :image, :marksheet,  maximum: 2.megabytes
  validate :rejection_reason_error
  validate :grade_presence


  def rejection_reason_error
    if (admission_status == "Selected" || admission_status == "Accepted" || admission_status == "Under Process")  && rejection_reason.present?
      errors.add(:rejection_reason, ": There can't be any rejection reason if the candidate is not rejected")
    end
    if admission_status == "Rejected" && !rejection_reason.present?
      errors.add(:rejection_reason, " Add rejection reason.")
    end
  end

  def grade_presence
    if admission_status == "Selected"
      unless grade.present?
        errors.add(:grade, " Please specify the grade in which candidate got admission")
      end
    else
      if grade.present?
        errors.add(:grade, " Grade can't be there if the candidate is not selected for admission")
      end
    end
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only:[:manage, :destroy]
  before_action :find_section_and_candidate , only:[:show, :edit, :update, :destroy, :manage]
  after_action :save_my_previous_url, only: [:edit]

  def index

    if current_user.admin?
      @candidates = Candidate.all
      @under_process_candidates = Candidate.where('admission_status="Under Process" or admission_status="Accepted" ')
      @selected_candidates = Candidate.where('admission_status="Selected"')
      @rejected_candidates = Candidate.where('admission_status="Rejected"')
    else
      @candidates = current_user.candidates
      @under_process_candidates = current_user.candidates.where('admission_status="Under Process" or admission_status="Accepted" ')
      @selected_candidates = current_user.candidates.where('admission_status="Selected"')
      @rejected_candidates = current_user.candidates.where('admission_status="Rejected"')
    end
  end

  def show
    @user = @candidate.user
    correct_user_or_admin
  end

  def select
    @sections = Section.all
  end

  def build
    @section = Section.find(params[:section])
    redirect_to new_section_candidate_path(@section)
  end

  def new
    @section = Section.find(params[:section_id])
    @candidate =@section.candidates.new
  end

  def create
    @section = Section.find(params[:section_id])
    @candidate = @section.candidates.new(candidate_params)
    @candidate.user_id = current_user.id
    @user = User.find_by_id(@candidate.user_id)

    if @candidate.save
      UserMailer.welcome_email(@user, @candidate).deliver_later
      flash[:notice] = "Candidate created successfully"
      redirect_to section_path(@section)
    else
      render('new')
    end
  end

  def edit
    correct_user_or_admin
  end

  def update
    @back = session[:my_previous_url]
    correct_user_or_admin
    @user = User.find_by_id(@candidate.user_id)
    if @candidate.update_attributes(candidate_params)

      if params[:candidate][:admission_status].present?
        if @candidate.admission_status == "Accepted"
          redirect_to new_section_candidate_appointment_path(@candidate.section, @candidate)
        elsif @candidate.admission_status == "Rejected"
          UserMailer.rejection_email(@user, @candidate).deliver_later
          flash[:notice] = "Candidate updated successfully"
          redirect_to(candidates_index_path)
        elsif @candidate.admission_status == "Selected"
          UserMailer.selection_email(@user, @candidate).deliver_later
          flash[:notice] = "Candidate updated successfully"
          redirect_to(candidates_index_path)
        end
      else
        flash[:notice] = "Candidate updated successfully"
        redirect_to @back
      end
    elsif params[:candidate][:admission_status].present?
      render ('manage')
    else
      render('edit')
    end
  end

  def destroy
    @candidate.destroy
    flash[:notice] = "Candidate destroyed successfully"
    redirect_to request.referer
  end

  def manage
  end

  private

  def candidate_params
    params.require(:candidate).permit(:name, :father_name, :mother_name, :education, :contact_address,
     :parent_contact_number, :alternate_parent_contact_number, :image, :marksheet, :admission_status,
      :rejection_reason, :grade)
  end

  def correct_user_or_admin
    unless @candidate.user_id == current_user.id || current_user.admin?
      redirect_to section_path(@section) and return
      flash[:danger]="You are not authorized"
    end
  end

  def admin_user
    unless current_user.admin?
      redirect_to(root_path)
      flash[:danger]="You are not authorized to perform this action"
    end
  end

  def find_section_and_candidate
    @section = Section.find(params[:section_id])
    @candidate = @section.candidates.find(params[:id])
  end

  def save_my_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
    session[:my_previous_url] = URI(request.referer || '').path
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= error_messages_for(f.object) %>
<% grades_array = ['Not Applicable', 'Kindergarten', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th'];
   section_grades = f.object.section.section_grades.split(',')
   min_grade = section_grades.first
   max_grade = section_grades.last
   min_index = grades_array.index(min_grade)
   max_index = grades_array.index(max_grade)

   if min_index == 1 && max_index == 1
     grades = grades_array[min_index-1..min_index-1]
   else
     grades = grades_array[min_index-1..max_index-1]
   end
   education_option = grades.each { |grade| [grade] } %>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <table class="table">
        <tr>
          <th>Section Name: </th>
          <td><%= @section.section_name %></td>
        </tr>
        <tr>
          <th><%= f.label :name, "Name" %></th>
          <td><%= f.text_field :name, class: 'form-control' %></td>
        </tr>
        <tr>
          <th><%= f.label :image, "Add passport size photo" %></th>
          <td><%= f.file_field :image %></td>
        </tr>
        <tr>
          <th><%= f.label :father_name, "Father's name" %></th>
          <td><%= f.text_field :father_name, class: 'form-control' %></td>
        </tr>
        <tr>
          <th><%= f.label :mother_name, "Mother's Name" %></th>
          <td><%= f.text_field :mother_name, class: 'form-control' %></td>
        </tr>
        <tr>
          <th><%= f.label :education, "Education" %></th>
          <td>
            <%= f.select(:education, options_for_select(education_option)) %>
          </td>
        </tr>
        <% unless min_index = 1 && max_index == 1  %>
          <tr>
            <th><%= f.label :marksheet, "Marksheet" %></th>
            <td><%= f.file_field :marksheet %></td>
          </tr>
        <% end %>
        <tr>
          <th><%= f.label :contact_address, "Contact Address" %></th>
          <td><%= f.text_area :contact_address, size: "40x3", class: 'form-control' %></td>
        </tr>
        <tr>
          <th><%= f.label :parent_contact_number, "Parent Contact Number" %></th>
          <td><%= f.telephone_field :parent_contact_number, class: 'form-control' %></td>
        </tr>
        <tr>
          <th><%= f.label :alternate_parent_contact_number, "Parent Alternate Contact Number" %></th>
          <td><%= f.telephone_field :alternate_parent_contact_number, class: 'form-control' %></td>
        </tr>
      </table>
    </div>
  </div>

app/views/candidates/edit.html.erb
<div class="container">
  <h2 class="text-center bg-info">Update Candidate</h2>
  <br>
  <%= form_for @candidate, url: section_candidate_path, html: { multipart: true } do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
    <div class="text-center">
      <%= f.submit "Update Candidate", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/candidates/index.html.erb
<div class="container">
  <% if @candidates.size > 0 %>
    <h2 class="text-center bg-info">Admission Status of Candidates</h2>
    <br>
    <% if @under_process_candidates.size > 0 %>
      <h4 class="text-primary bg-gray">Candidates whose admission status is under process</h4>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Father's Name</th>
          <th>Section Name</th>
          <th>Admission Status</th>
        </tr>
        <% @under_process_candidates.each do |candidate| %>
          <tr>
            <td><%=link_to candidate.name, section_candidate_path(candidate.section,candidate)  %></td>
            <td><%= candidate.father_name %></td>
            <td><%= candidate.section.section_name %></td>
            <% if candidate.admission_status == 'Accepted' && candidate.appointment.present? %>
              <td>Application accepted and appointment scheduled</td>
            <% else %>
              <td>Under Process</td>
            <% end %>
            <% if current_user.admin? %>
              <td><%= link_to "Manage Candidate", manage_section_candidate_path(candidate.section,candidate), class: "btn btn-info btn-sm" %></td>
            <% end %>
            <td><%= link_to "Edit Candidate", edit_section_candidate_path(candidate.section,candidate), class: "btn btn-info btn-sm" %></td>
            <% if current_user.admin? %>
              <td><%= link_to 'Destroy candidate', [candidate.section, candidate], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-info btn-sm text-danger' %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>

    <% if @selected_candidates.size > 0 %>
      <h4 class="text-primary bg-gray">Selected Candidates</h4>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Father's Name</th>
          <th>Section Name</th>
          <th>Admission Status</th>
          <th>Grade</th>
        </tr>
        <% @selected_candidates.each do |candidate| %>
          <tr>
            <td><%=link_to candidate.name, section_candidate_path(candidate.section,candidate)  %></td>
            <td><%= candidate.father_name %></td>
            <td><%= candidate.section.section_name %></td>
            <td><%= candidate.admission_status %></td>
            <td><%= candidate.grade %></td>
            <td><%= link_to "Edit Candidate", edit_section_candidate_path(candidate.section,candidate), class: "btn btn-info btn-sm" %></td>
            <% if current_user.admin? %>
              <td><%= link_to 'Destroy candidate', [candidate.section, candidate], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-info btn-sm text-danger' %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>

    <% if @rejected_candidates.size > 0 %>
      <h4 class="text-primary bg-gray">Rejected Candidates</h4>
      <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Father's Name</th>
          <th>Section Name</th>
          <th>Admission Status</th>
          <th>Rejection Reason</th>
        </tr>
        <% @rejected_candidates.each do |candidate| %>
          <tr>
            <td><%=link_to candidate.name, section_candidate_path(candidate.section,candidate)  %></td>
            <td><%= candidate.father_name %></td>
            <td><%= candidate.section.section_name %></td>
            <td><%= candidate.admission_status %></td>
            <td><%= candidate.rejection_reason %></td>
            <td><%= link_to "Edit Candidate", edit_section_candidate_path(candidate.section,candidate), class: "btn btn-info btn-sm" %></td>
            <% if current_user.admin? %>
              <td><%= link_to 'Destroy candidate', [candidate.section, candidate], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-info btn-sm text-danger' %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% end %>
  <% else %>
    <h4 class="bg-gray">No candidates present</h4>
  <% end %>
</div>

app/views/candidates/manage.html.erb
<div class="container">

  <% if @candidate.appointment.present? %>
    <% if @candidate.errors.size > 0 %>
      <%= error_messages_for(@candidate) %>
      <%
        @grades = ['Not Applicable', 'Kindergarten', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th']
        @index = @grades.index("#{@candidate.education}")
        @grade = @grades[@index+1]
      %>
      <h2 class="bg-info text-center">Manage Candidate Admission</h2>
      <%= form_for @candidate, url: section_candidate_path do |f| %>
        <table class="table">
          <tr class="admission-status">
            <th><%= f.label(:admission_status, "Admission Status") %></th>
            <td><%= f.select(:admission_status, ['Selected', 'Rejected']) %></td>
          </tr>
          <tr class="rejection-reason">
            <th><%= f.label(:rejection_reason)%></th>
            <td><%= f.text_area :rejection_reason, size: "40x3" %></td>
          </tr>
          <tr class="grade">
            <th><%= f.label(:grade, "Admission in grade")%></th>
            <td><%= f.select :grade, ['', @grade] %></td>
          </tr>
        </table>
        <div class="text-center">
        <%= f.submit "Manage Candidate Admission" ,class:"btn btn-info" %>
        </div>
      <% end %>
    <% else %>
      <%
        @grades = ['Not Applicable', 'Kindergarten', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th']
        @index = @grades.index("#{@candidate.education}")
        @grade = @grades[@index+1]
      %>
      <% if @candidate.admission_status == "Selected" %>
        <h2 class="bg-info text-center">Manage Candidate Admission</h2>
        <h4 class="bg-gray">Candidate is already selected for admission.</h4>
      <% elsif @candidate.admission_status == "Rejected" %>
        <h2 class="bg-info text-center">Manage Candidate Admission</h2>
        <h4 class="bg-gray">Candidate is already rejected.</h4>
      <% elsif @candidate.appointment.datetime > Time.now %>
        <h2 class="bg-info text-center">Manage Candidate Admission</h2>
        <h4 class="bg-gray">Appointment is scheduled for the candidate. You can manage candidate's admission once the appointment is over. </h4>
      <% else %>
        <h2 class="bg-info text-center">Manage Candidate Admission</h2>
        <%= form_for @candidate, url: section_candidate_path do |f| %>
          <table class="table">
            <tr class="admission-status">
              <th><%= f.label(:admission_status, "Admission Status") %></th>
              <td><%= f.select(:admission_status, ['Selected', 'Rejected']) %></td>
            </tr>
            <tr class="rejection-reason">
              <th><%= f.label(:rejection_reason)%></th>
              <td><%= f.text_area :rejection_reason, size: "40x3" %></td>
            </tr>
            <tr class="grade">
              <th><%= f.label(:grade, "Admission in grade")%></th>
              <td><%= f.select :grade, ['', @grade] %></td>
            </tr>
          </table>
          <div class="text-center">
          <%= f.submit "Manage Candidate Admission" ,class:"btn btn-info" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <% if @candidate.errors.size > 0 %>
      <%= error_messages_for(@candidate) %>
      <br>
      <% if @candidate.marksheet.present? %>
        <table class="table">
          <tr>
            <th class="text-center">Candidate's Marksheet</th>
          </tr>
          <tr>
            <td class="text-center"><%= image_tag @candidate.marksheet.url(:ex_large) %></td>
          </tr>
        </table>
      <% end %>
      <h2 class="text-center bg-info">Manage Candidate's Application</h2>
      <br>
      <%= form_for @candidate, url: section_candidate_path do |f| %>
        <table class="table">
          <tr class="application-status">
            <th><%= f.label(:admission_status, "Application Status") %></th>
            <td><%= f.select :admission_status,options_for_select(['Accepted', 'Rejected'])%></td>
          </tr>
          <tr class="rejection">
            <th><%= f.label(:rejection_reason )%></th>
            <td><%= f.text_area :rejection_reason, size: "40x3" %></td>
          </tr>
        </table>
        <div class="text-center save">
        <%= f.submit "Save and Schedule appointment", class:"btn btn-info" %>
        </div>
        <div class="text-center reject">
        <%= f.submit "Reject Candidate", class:"btn btn-info" %>
        </div>
      <% end %>
    <% else %>
      <% if @candidate.admission_status == "Rejected" %>
        <h2 class="bg-info text-center">Manage Candidate Admission</h2>
        <h4 class="bg-gray">Candidate is already rejected.</h4>
      <% end %>
      <%= error_messages_for(@candidate) %>
      <br>
      <% if @candidate.marksheet.present? %>
        <table class="table">
          <tr>
            <th class="text-center">Candidate's Marksheet</th>
          </tr>
          <tr>
            <td class="text-center"><%= image_tag @candidate.marksheet.url(:ex_large) %></td>
          </tr>
        </table>
      <% end %>
      <h2 class="text-center bg-info">Manage Candidate's Application</h2>
      <br>
      <%= form_for @candidate, url: section_candidate_path do |f| %>
        <table class="table">
          <tr class="application-status">
            <th><%= f.label(:admission_status, "Application Status") %></th>
            <td><%= f.select :admission_status,options_for_select(['Accepted', 'Rejected'])%></td>
          </tr>
          <tr class="rejection">
            <th><%= f.label(:rejection_reason )%></th>
            <td><%= f.text_area :rejection_reason, size: "40x3" %></td>
          </tr>
        </table>
        <div class="text-center save">
        <%= f.submit "Save and Schedule appointment", class:"btn btn-info" %>
        </div>
        <div class="text-center reject">
        <%= f.submit "Reject Candidate", class:"btn btn-info" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/candidates/new.html.erb
<div class="container">
  <h2 class="text-center bg-info">Add candidate details</h2>
  <br>
  <%= form_for @candidate, url: section_candidates_path, html: { multipart: true } do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
    <div class="text-center">
      <%= f.submit "Apply for admission", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/candidates/select.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2 class="bg-info text-center">Select section</h2>
      <%= form_tag(candidates_build_path, method: :post) %>
      <table class="table">
        <tr>
          <td class="text-right"><label for="section">Section :</td><td class="text-center"></label><%= select_tag "section", options_from_collection_for_select(@sections,"id","section_name") %></td>
        </tr>
        <tr>
          <td colspan="2" class="text-center">
            <%= submit_tag "Apply under this section", class:"btn btn-info" %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<div class="container">
  <% if @candidate.present? %>
    <h2 class="text-center bg-info">Candidate Details</h2>
    <br>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 gray-border">
        <table class="table text-center">
          <tr>
            <th>Candidate's Photo</th>
            <td><%= image_tag @candidate.image.url(:thumb), class: "passport-size" %></td>
          </tr>
          <tr>
            <th>Name</th>
            <td><%= @candidate.name %></td>
          </tr>
          <tr>
            <th>Father's Name</th>
            <td><%= @candidate.father_name %></td>
          </tr>
          <tr>
            <th>Mother's Name</th>
            <td><%= @candidate.mother_name %></td>
          </tr>
          <% unless @candidate.education == "Not Applicable" %>
            <tr>
              <th>Education</th>
              <td><%= @candidate.education %></td>
            </tr>
          <% end %>
          <tr>
            <th>Contact Address</th>
            <td><%= @candidate.contact_address %></td>
          </tr>
          <tr>
            <th>Parent's Contact Number</th>
            <td><%= @candidate.parent_contact_number %></td>
          </tr>
          <% if @candidate.alternate_parent_contact_number %>
            <tr>
              <th>Parent's Contact Number</th>
              <td><%= @candidate.alternate_parent_contact_number %></td>
            </tr>
          <% end %>
        </table>
        <div class="text-right">
          <%= link_to "Edit candidate", edit_section_candidate_path(@candidate.section,@candidate),class:"btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>