config/routes.rb
Rails.application.routes.draw do

  root 'access#menu'
  get 'fee/index'
  get 'sessions/new'
  get 'appointments/index'
  get 'payments/index'
  get 'access/menu'
  get 'candidates/index'
  get 'fees/new'
  post 'candidates/build'
  get 'candidates/select'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :eligibilities, except: [:show]
  resources :notices
  resources :users
  resources :fees
  resources :sections do

    resources :candidates do
      get 'manage', on: :member
      resources :appointments
      resources :payments
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :candidate

  validates :candidate_id, uniqueness: { message: "You have already scheduled an appointment" }
  validate :valid_date
  validates :venue, presence: true, length: { minimum: 10 }

  private

  def valid_date
    if datetime < Time.now
      errors.add(:base, "Appointment can't be in the past")
    end
  end

end

app/models/candidate.rb
class Candidate < ApplicationRecord

  has_one :appointment, dependent: :destroy
  has_many :payments, dependent: :destroy
  belongs_to :section
  belongs_to :user

  has_attached_file :image, styles: { thumb: "100x100#" }
  has_attached_file :marksheet, styles: { ex_large: "1000x1000>", medium: "300x300>" }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :marksheet, content_type: /\Aimage\/.*\z/
  validates :name, :father_name, :mother_name , presence: true, length: { maximum: 50 }
  validates :education, :contact_address, :parent_contact_number,:image, presence: true
  validates :parent_contact_number,:alternate_parent_contact_number, numericality: true, format: { with: /\A[789]\d{9}\z/ }
  validates_size_of :image, :marksheet,  maximum: 2.megabytes
  validate :rejection_reason_error
  validate :grade_presence


  def rejection_reason_error
    if (admission_status == "Selected" || admission_status == "Accepted" || admission_status == "Under Process")  && rejection_reason.present?
      errors.add(:rejection_reason, ": There can't be any rejection reason if the candidate is not rejected")
    end
    if admission_status == "Rejected" && !rejection_reason.present?
      errors.add(:rejection_reason, " Add rejection reason.")
    end
  end

  def grade_presence
    if admission_status == "Selected"
      unless grade.present?
        errors.add(:grade, " Please specify the grade in which candidate got admission")
      end
    else
      if grade.present?
        errors.add(:grade, " Grade can't be there if the candidate is not selected for admission")
      end
    end
  end

end

app/models/eligibility.rb
class Eligibility < ApplicationRecord

  validates :title, :criteria, presence: true
  validates :title, :criteria, length: { minimum:5 }

end

app/models/fee.rb
class Fee < ApplicationRecord

  belongs_to :section

  validates :fee_name, :fee_amount, presence: true
  validates :fee_amount, numericality: { only_integer: true }
end

app/models/notice.rb
class Notice < ApplicationRecord

  validates :notice_title, :content, presence: true
  validates :notice_title, :content, length: { minimum:5 }

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :candidate

  has_attached_file :payment_image, styles: { medium: "600x600>" }

  validates_attachment_content_type :payment_image, content_type: /\Aimage\/.*\z/
  validates :payment_status, :payment_image, :payment_mode, :amount, presence: true
  validates :amount, numericality: { only_integer: true }

end

app/models/section.rb
class Section < ApplicationRecord
  has_many :candidates, dependent: :destroy
  has_many :fees, dependent: :destroy
  validates :section_name, uniqueness: true
  validates :section_name, :section_grades, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :candidates, dependent: :destroy

  has_secure_password

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, except:[:index]

  def index
    @sections = Section.all
    @fees = Fee.all
  end

  def new
    @sections = Section.all
    @fee = Fee.new
  end

  def create
    @sections = Section.all
    @fee = Fee.new(fee_params)
    if @fee.save
      flash[:notice] = "Fee added successfully"
      redirect_to fees_path
    else
      render 'new'
    end
  end

  def edit
    @sections = Section.all
    @fee = Fee.find(params[:id])
  end

  def update
    @sections = Section.all
    @fee = Fee.find(params[:id])
    if @fee.update_attributes(fee_params)
      flash[:notice] = "Fee updated successfully"
      redirect_to fees_path
    else
      render 'edit'
    end
  end

  def destroy
    @fee = Fee.find(params[:id])
    @fee.destroy
    flash[:notice] = "Fee destroyed successfully"
    redirect_to fees_path

  end

  private

  def fee_params
    params.require(:fee).permit(:section_id, :fee_amount, :fee_name)
  end

  def admin_user
    unless current_user.admin?
      redirect_to(root_path)
      flash[:danger]="You are not authorized to perform this action"
    end
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(partial: 'application/error_messages', locals: { object: object })
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/fee_helper.rb
module FeeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer bg-info container-fluid">
		<div class="container">
			  <span class="copyright-privacy-policy">
				  <span class="copyright">Marigold International school &copy; 2017</span>
				  <a href="#" class="privacy-policy"> Privacy Policy</a>
			  </span>
		</div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid absolute text-center hidden-xs">
  <% if logged_in? %>
    <%= link_to (image_tag "logo.png", class:"logo-height-1"), root_path %>
  <% else %>
    <%= link_to (image_tag "logo.png", class:"logo-height-2"), root_path %>
  <% end %>
  <%= link_to "Marigold International School", root_path, class:"text-bigger no-underline"%>
</div>
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right text-center text-big">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to("Appointments", appointments_index_path)%></li>
            <li><%= link_to "Payments", payments_index_path %></li>
          <% end %>
          <li class="dropdown btn-group">
            <a class="dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "user.jpg" ,class:"user-width" %>My account
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><%= link_to "My candidates", current_user, class:"dropdown-item text-center" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class:"dropdown-item text-center" %></li>
              <li><%= link_to "Log out", logout_path, method: :delete, class:"dropdown-item text-center" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABC School</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body class="bg-body">
    <%= render 'layouts/header' %>
    <% if !flash[:notice].blank? %>
      <div class="text-center">
        <h4 class="bg-green"><%= flash[:notice] %></h4>
      </div>
    <% end %>
    <% if !flash[:danger].blank? %>
      <div class="text-center">
        <h4 class="bg-red text-danger"><%= flash[:danger] %></h4>
      </div>
    <% end %>
    <div class="wrapper">
      <%= yield %>
      <div class="push">
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>